lakeforge:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: lakeforge.duckdb
      threads: 4
      extensions:
        - httpfs
      settings:
        s3_region: us-east-1
        s3_access_key_id: minio
        s3_secret_access_key: minio123
        s3_endpoint: localhost:9000
        s3_use_ssl: false
        s3_url_style: path
